[build]
  command = "npm run build"
  publish = "build"
  functions = ".netlify/functions-internal"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/sveltekit-render"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"