const PUBLIC_SUPABASE_URL = "https://dbaeqkqqouvdzcmngtml.supabase.co";
const PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRiYWVxa3Fxb3V2ZHpjbW5ndG1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUwODU4MjAsImV4cCI6MjA1MDY2MTgyMH0.3UfrYVfa7sxwGK3tGVgCzM6PHMkj-9d8cI56RhGnZYI";
export {
  PUBLIC_SUPABASE_URL as P,
  PUBLIC_SUPABASE_ANON_KEY as a
};
